global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'tempo'
    static_configs:
    - targets: ['tempo:3200']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']

  - job_name: 'actor'
    metrics_path: /metrics
    static_configs:
    - targets: ['actor:8081']

  - job_name: 'movie'
    metrics_path: /metrics
    static_configs:
    - targets: ['movie:8082']